### ISSUE TITLE
Fix download deb package

### ISSUE THREAD

**Issue by ByJacob** [andrelohmann/ansible-role-wkhtmltopdf#1]
1. Change base url - `https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download`
2. Use `wkhtmltopdf_patch_release` and `wkhtmltopdf_full_release` variable
```yaml
- name: Download wkhtmltopdf package for Linux 32 bits
  get_url:
    url: "https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/{{ wkhtmltopdf_patch_release }}/wkhtmltox_{{ wkhtmltopdf_full_release }}.{{ ansible_distribution_release }}_i386.deb"
    dest: /tmp/wkhtmltopdf.deb
  when: "'32' in ansible_architecture and 'Linux' == ansible_system"

- name: Download wkhtmltopdf package for Linux 64 bits
  get_url:
    url: "https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/{{ wkhtmltopdf_patch_release }}/wkhtmltox_{{ wkhtmltopdf_full_release }}.{{ ansible_distribution_release }}_amd64.deb"
    dest: /tmp/wkhtmltopdf.deb
  when: "'64' in ansible_architecture and 'Linux' == ansible_system"
```
